### ISSUE TITLE
outline arrows

### ISSUE THREAD

**Issue by walkoffhomerun** [bqworks/slider-pro#212]
i have tried to use my usual CSS methods to outline arrows but these arrows are not typical font arrows and instead 2 lines merged to make an arrow and for some reason the usual CSS methods do not work.

-webkit-text-stroke: 1px black;
text-shadow: -1px -1px 0 #000, 1px -1px 0 #000, -1px 1px 0 #000, 1px 1px 0 #000;

Is there a way to add an outline to the arrows so they are visible on white backgrounds -OR- convert them to standard font based arrows such as FontAwesome Chevron which is an identical arrow ???

**Comment by davidghi** [comment]
Hi. Your method doesn't work because the shadow is applied to each individual line, not to the whole shape. However, you can change the default CSS that I used for the arrows to use a font instead.

Cheers!

**Comment by walkoffhomerun** [comment]
So where do i find where to change the lines to a font? Is it in the js or a css file?

**Comment by walkoffhomerun** [comment]
-OR- would it be easier to add a small colored box around the arrows when they are hovered over?  that may be alot easier.  but i dont know where to do either that or change the lines to the fonts.  i looked at the CSS file and it has a ton of sections to draw those angles of the arrows.  not as easy as just changing to a font.  that is why the background box may be a better solution

**Comment by davidghi** [comment]
It's possible both to replace the arrows with fonts or to add a background rectangle. For the first solution, you need this CSS in order to remove the current style:

```css
.sp-next-arrow:after, .sp-previous-arrow:after,
.sp-next-arrow:before, .sp-previous-arrow:before {
    content: none;
}
```

Then you need some JavaScript in order to add the class names for the fontawesome arrows on runtime:

```javascript
jQuery( '.sp-next-arrow' ).first().addClass( 'fa fa-arrow-right' );
jQuery( '.sp-previous-arrow' ).last().addClass( 'fa fa-arrow-left' );
```

For the second solution, you need to adjust the current CSS:

```css
.sp-arrow {
    padding: 10px;
    transition: all 1s;
}

.sp-arrow:hover {
    background-color: #F00;
}

.sp-next-arrow:after, .sp-next-arrow:before,
.sp-previous-arrow:after, .sp-previous-arrow:before {   
    width: 20%;
    height: 30%;
}

.sp-previous-arrow:before, .sp-next-arrow:before {
    top: 20%;
}
```

This code is only for demonstration purposes; you might want to adjust the values in your implementation.

Cheers
