### ISSUE TITLE
When resize destroy slide and show each image

### ISSUE THREAD

**Issue by brunogiliberto** [bqworks/slider-pro#240]
Hi there,

I know that is very rare,  but I want to show a slider on a desktop version and when resized to mobile version show each image separately, like in a gallery. is that possible?

http://weddings.brunogiliberto.com

Thanks in advance

**Comment by walkoffhomerun** [comment]
i did the exact same thing on my existing website.  on desktop screens i have slider pro working and on mobile i turn it off and have a separate div with smaller images loaded.  so you created 2 sections the way i did it and with CSS you turn off the mobile display div when on desktop size screens and you turn off desktop display div when on mobile screens.

so here is my basic div layout:

```
<div class="desktop_only_displays">
     <div id="example2" class="slider-pro">
	<div class="sp-slides">
	   <div class="sp-slide">
		<img class="sp-image" src="1x1-Wht.gif" data-src="your_fullsize_image.jpg" alt="image description">

..... more images
   </div>
</div>


<div id="mobile_only_displays">
         <img src="image1.jpg" alt="image description">
	 <img src="image2.jpg" alt="image description">
         ..... more images
</div>
```


then with @media queries based on screen size you turn on and off the 2 div holders "desktop_only_displays" and "mobile_only_displays"

**this area of a CSS file will turn OFF desktop display and turn on the mobile display div**
@media only screen and (max-width: 479px)
.desktop_only_displays {display: none !important}
#mobile_only_displays {display: block;}

**this are of a CSS file will be the default for leaving the desktop display on and active but turn OFF the mobile display.  Notice there is NO @media query because it is full screen and you want the mobile display OFF at all times UNLESS in my example you hit 479 pixels or less which is the @media query shown above**
#mobile_only_displays {display: none;}

**Comment by brunogiliberto** [comment]
Thanks a lot for your time @walkoffhomerun. But in my case I have information in each image on my slide (like titles) and I don't want to have extra code and upload the info two times. With your option in my case is probably better to have another template for mobile devices but google already said that if your web isn't responsive the will not publish it on their list.

So I'm still waiting if there is any option to split de slide and show every image separately as I'm repositioning slides and adding or subtracting pictures very often.

If you can see my website I just have one big slide :)

**Comment by brunogiliberto** [comment]
Thanks a lot for your time @walkoffhomerun. But in my case I have information in each image on my slide (like titles) and I don't want to have extra code and upload the info two times. With your option in my case is probably better to have another template for mobile devices but google already said that if your web isn't responsive the will not publish it on their list.

So I'm still waiting if there is any option to split de slide and show every image separately as I'm repositioning slides and adding or subtracting pictures very often.

If you can see my website I just have one big slide :)

**Comment by davidghi** [comment]
Hi. You can use CSS to modify the layout of the slider on smaller screens. Here's an example:

```css
@media(max-wdith: 500px) {
    .sp-slide {
        left: 0 !important;
        position: relative;
        height: auto !important;
        margin-bottom: 10px;
    }

    .sp-slides {
        transform: translate3d(0px, 0px, 0px) !important;
    }

    .sp-mask {
        height: auto !important;
    }

    .sp-image {
        max-width: 100% !important;
        height: auto !important;
    }

    .sp-image-container {
        height: auto !important;
    }
}
```

Cheers!
