### ISSUE TITLE
Show caption only on mouseover slide

### ISSUE THREAD

**Issue by t-book** [bqworks/slider-pro#264]
Hi,

thanks for the great slider! One question. Is there already something implemented that a sp-layer with captions only shows when the mouse is over the image? 

Find a fiddle here: https://jsfiddle.net/2sa3t5uv/2/
The caption of the third image is always visible but should only be shown when the mouse hovers and the slidershow is paused!

thanks!

**Comment by davidghi** [comment]
Hi. You can use this CSS:

```css
.sp-layer {
    opacity: 0 !important;
    transition: opacity 0.5s;
}

.sp-slide:hover .sp-layer {
    opacity: 1 !important;
}
```

Cheers!
