### ISSUE TITLE
Thumbnails in portrait orientation are cropped

### ISSUE THREAD

**Issue by baumann74** [bqworks/slider-pro#274]
With the default settings thumbnails with portrait orientation (height > width) are cropped vertically. Is it possible to avoid this cropping? I am looking for a setting like 'imageScaleMode=contain' but for the thumbnails?

Thanks in advance,
Anders Baumann

**Comment by davidghi** [comment]
Hi Anders,

The thumbnails don't have an option for controlling the scaling mode, but you can use CSS force something like 'contain':

```css
.sp-thumbnail {
    height: 100% !important;
    width: auto !important;
    margin: 0 !important;
}
```

However, this will create variable spaces between thumbnails.

Cheers!
