### ISSUE TITLE
Change the fullscreen button

### ISSUE THREAD

**Issue by sbellanger** [bqworks/slider-pro#282]
Hello, 
It's possible to change the fullscreen button ? 
or the color ? I don't find it in the css ...
The button is grey, and I often I can't see it
thanks

**Comment by davidghi** [comment]
Hi. You can change the button or the color. To change the color you can use this simple CSS:

```css
.sp-full-screen-button:before {
     color: #F00;
}
```

Cheers!
