### ISSUE TITLE
See captions in fullscreen mode

### ISSUE THREAD

**Issue by padisio** [bqworks/slider-pro#297]
Is it possible to see the captions over the image in fullscreen mode and as normal caption in reduced mode?
thanks

**Comment by davidghi** [comment]
Yes, it's possible with CSS:

```css
.sp-full-screen .sp-caption-container {
    position: relative;
    margin-top: -100px;
}
```

Best,
David
