### ISSUE TITLE
Center Image inside slide

### ISSUE THREAD

**Issue by jasperf** [bqworks/slider-pro#324]
We have `autoHeight:false` and `centerImage: true,` inside a slider image with `height:100%` and `width:100%` and margins set to `0`. 

```css
element {
    width: 100%;
    height: 100%;
    margin-left: 0px;
    margin-top: 0px;
    margin-bottom: 0px;
}
```
The image (505x600px orginal size) is inside a `sp-image-container` with generated dimensions `height: 400px; width: 641px;`:

```html
<div class="sp-image-container" style="height: 400px; width: 641px;">
<img data-v-3568e6ce="" src="/uploads/275/Logo/Flightcases/611d497f4769a.jpg" class="sp-image" 
data-default="/uploads/275/Logo/Flightcases/611d497f4769a.jpg" 
style="width: 100%; height: 100%; margin-left: 0px; margin-top: 0px;margin-bottom: 0px;">
</div> 
```
In a landscape sized slider and slide a portrait image is kind of squashed. And more importantly, we do not see it centered. 

When I change height to `auto` the image is clear, but then the position is off. It is only partly shown that is. Only the top shows:

![image height auto cropped](https://user-images.githubusercontent.com/344138/130307537-5fd3370a-9b4f-4be5-bb86-623e453bef76.png)

When we set the width to `auto` and height to a `100%` I can see the entire image, but then the image and background only take up 50% of the width of the rectangular slider:

![width auto](https://user-images.githubusercontent.com/344138/130307758-cba13875-665a-4850-8b7c-d4c1c9753dc9.png)

However, for the rectangular images that setting would cause the image to be partly cut at the right side. So for landscape this would be better:
```css
element {
    width: 100%;
    height: auto;
    margin-left: 0px;
    margin-top: 0px;
}
```
but we still miss part of the slider here yet again:

![height auto for landscape image](https://user-images.githubusercontent.com/344138/130307858-7dec31fa-57bf-4d50-87bd-7e2195945939.png)

How can I _just_ center this portrait sized image in our landscape slider with it filling the size set for the slides?
